# Generated by Django 3.1.7 on 2021-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210405_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(to='core.Specification'),
        ),
    ]
