# Generated by Django 3.1.7 on 2021-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210405_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular pizza'), ('Square', 'Square pizza')], max_length=13),
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
    ]
