# Generated by Django 3.1.7 on 2021-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210406_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular pizza'), ('square', 'Square pizza')], max_length=13),
        ),
    ]
